version: '3.8'

services:
  vllm-server:
    image: vllm/vllm-openai:latest
    ports:
      - "30000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      --model facebook/opt-125m
      --host 0.0.0.0
      --port 8000